// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSjIdZOyOCosvZ0RRDVutXwVXoJjI7_RY',
    appId: '1:755545286312:web:02aaec1666f99b4875049d',
    messagingSenderId: '755545286312',
    projectId: 'inventory-management-sys-e6b8a',
    authDomain: 'inventory-management-sys-e6b8a.firebaseapp.com',
    storageBucket: 'inventory-management-sys-e6b8a.appspot.com',
    measurementId: 'G-YYHE6BDSVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwd6A61a9jvcH6kJUQ0oxQf7c0dEEK8Hc',
    appId: '1:755545286312:android:5707fab7be7363ae75049d',
    messagingSenderId: '755545286312',
    projectId: 'inventory-management-sys-e6b8a',
    storageBucket: 'inventory-management-sys-e6b8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSe6jzrIhPDqvXv9eDBdYeLmVhywN_-Hg',
    appId: '1:755545286312:ios:cd453ebee37f054175049d',
    messagingSenderId: '755545286312',
    projectId: 'inventory-management-sys-e6b8a',
    storageBucket: 'inventory-management-sys-e6b8a.appspot.com',
    iosBundleId: 'com.example.appCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSe6jzrIhPDqvXv9eDBdYeLmVhywN_-Hg',
    appId: '1:755545286312:ios:53474209b00c736575049d',
    messagingSenderId: '755545286312',
    projectId: 'inventory-management-sys-e6b8a',
    storageBucket: 'inventory-management-sys-e6b8a.appspot.com',
    iosBundleId: 'com.example.appCode.RunnerTests',
  );
}
